//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleSetup3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccredDriverView
    {
        public string Class { get; set; }
        public string Name { get; set; }
        public string FleetNo { get; set; }
        public Nullable<System.DateTime> DateObtained { get; set; }
        public Nullable<System.DateTime> ValidFromDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int ID { get; set; }
    }
}
