//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleSetup3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacity
    {
        public int ID { get; set; }
        public string FleetNo { get; set; }
        public int Pallets { get; set; }
        public int Spaces { get; set; }
        public decimal CubicSpace { get; set; }
        public Nullable<decimal> InternalHeight { get; set; }
        public Nullable<decimal> InternalWidht { get; set; }
        public Nullable<decimal> InternalLenght { get; set; }
        public decimal Tare { get; set; }
        public decimal GVM { get; set; }
        public decimal GCM { get; set; }
        public bool IsMainCapacity { get; set; }
    
        public virtual FleetAsset FleetAsset { get; set; }
    }
}
