//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleSetup3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegTrailerView
    {
        public string FleetNo { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ValidFromDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string AlertOperation { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateObtained { get; set; }
        public string LicenseNo { get; set; }
        public int ID { get; set; }
    }
}
