//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleSetup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalFields
    {
        public int ID { get; set; }
        public string FleetNo { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual FleetAsset FleetAsset { get; set; }
    }
}
